AWSTemplateFormatVersion:    '2010-09-09'
Transform:                   AWS::Serverless-2016-10-31
Description:                 Serverless application distributing patch notes for NCLS Development's Orca solution, using AWS CloudFormation.
Resources:
  GetFunction:
    Type:                    AWS::Serverless::Function
    Properties:
      Handler:               index.get
      Runtime:               nodejs6.10
      Policies:              AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME:        !Ref Table
      Events:
        GetResource:
          Type:              Api
          Properties:
            Path:            /{version}
            Method:          get
  PutFunction:
    Type:                    AWS::Serverless::Function
    Properties:
      Handler:               index.put
      Runtime:               nodejs6.10
      Policies:              AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:        !Ref Table
      Events:
        PutResource:
          Type:              Api
          Properties:
            Path:            /{version}
            Method:          put
  DeleteFunction:
    Type:                    AWS::Serverless::Function
    Properties:
      Handler:               index.delete
      Runtime:               nodejs6.10
      Policies:              AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:        !Ref Table
      Events:
        DeleteResource:
          Type:              Api
          Properties:
            Path:            /{version}
            Method:          delete
  Table:
    Type:                    AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Type:                'String'
        Name:                'version'
      ProvisionedThroughput:
        ReadCapacityUnits:   5 # default
        WriteCapacityUnits:  5 # default
